server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shop_db;MODE=MySQL;NON_KEYWORDS=VALUE,DESC,GROUP;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
  sql:
    init:
      mode: always
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: shopsecretkeymustbelongerthan32chars
  expiration: 86400
